import React from "react"

import Layout from "../components/layout"
import SEO from "../components/seo"

const IndexPage = () => (
    <Layout>
        <SEO title="Home"/>

        <section className="phpdocumentor-section">
            <section className="eight phpdocumentor-columns phpdocumentor-content">
                <article className="content-overview tab-content">

                    <section id="why-use-phpdocumentor" className="tab-pane active">
                        <section>
                            <h2>What is phpDocumentor?</h2>
                            <p>
                                phpDocumentor is a tool that makes it possible to generate documentation directly from
                                your PHP source code. With this you can provide your consumers with more information
                                regarding the functionality embedded within your source and not just what is usable to
                                them from your user interface.
                            </p>

                            <p>
                                Documentation generated by phpDocumentor does not aim to be a replacement for
                                conventional documentation but is rather supplemental, or reference, documentation.
                                This proves to be useful in the following example situations:
                            </p>
                            <ul>
                                <li>
                                    Sets of libraries or applications providing an API, such as phpDocumentor 2 itself
                                </li>
                                <li>Frameworks, such as Zend Framework or Symfony</li>
                                <li>Pluggable architectures, such as WordPress or PyroCMS</li>
                                <li>
                                    Long-running, complex projects, to help you find the right function or method for
                                    the job
                                </li>
                            </ul>
                        </section>
                        <section>
                            <h2>Templates</h2>

                            <p>
                                phpDocumentor contains an incredibly flexible template system which enables you to
                                alter your output in any way imaginable. This can range from simply applying your own
                                branding for the HTML output by merely altering a couple of CSS files to determining
                                which types of output are generated and where they are made available.
                            </p>
                        </section>
                    </section>
                </article>
            </section>

            <section className="four phpdocumentor-columns" id="quickstart">
                <h2>Installing</h2>
                <article>
                    <h3>As a PHAR</h3>
                    <p>
                        <a href="http://phpdoc.org/phpDocumentor.phar">
                            All you need to do is download the phar binary.
                        </a>
                    </p>
                    <p>That's it. Really.</p>
                </article>
                <article><h3>Manually</h3>
                    <p>To do a manual installation, follow these steps</p>
                    <ol>
                        <li>
                            Locate the latest release on the
                            <a href="https://github.com/phpDocumentor/phpDocumentor2/releases">
                                releases page for phpDocumentor2 on GitHub
                            </a>
                        </li>
                        <li>Download the attached tarball (not the source code!)</li>
                        <li>Extract the downloaded tarball into your destination directory.</li>
                    </ol>
                    <p>
                        After you have done the above can the executable be found at
                        <code>bin/phpdoc.php</code> in the installation directory.
                    </p>
                </article>
            </section>
        </section>
    </Layout>
);

export default IndexPage
